---
  - name: start elasticsearch
    systemd:
      name: elasticsearch
      enabled: yes
      state: started

  - name: restart elasticsearch
    systemd:
      name: elasticsearch
      state: restarted

  - name: stop elasticsearch
    systemd:
      name: elasticsearch
      state: stopped
